## Notebook 02: Creating Logical Tables

In this notebook, the raw transactional dataset is split into logical tables
(customers, products, orders, payment_methods).

The goal is to simulate a relational database structure and prepare the data
for loading into PostgreSQL.

## Why split the data into tables?

The original CSV file contains denormalized transactional data.
In real-world analytics projects, such data is usually stored in a relational
database with separate tables for different entities.

By splitting the data into logical tables, we:
- reduce redundancy,
- improve data clarity,
- and make the dataset suitable for SQL-based analysis.

In [ ]:
# load the dataset
import pandas as pd
df = pd.read_csv('1_data/raw/amazon_sales.csv')

## Create customers table

The customers table is designed to contain one row per customer.

Although the same customer may appear multiple times in the raw dataset
(with different orders or location details), we deduplicate this table
using CustomerID as the primary key to ensure a clean dimension table.

In [2]:
# Customers: one row per customer (deduplicated by CustomerID)
df_customers = (
    df[
        [
            "CustomerID",
            "CustomerName",
            "City",
            "State",
            "Country"
        ]
    ]
    .drop_duplicates(subset="CustomerID")
    .reset_index(drop=True)
)

df_customers.head()

   CustomerID   CustomerName         City State        Country
0  CUST001504  Vihaan Sharma   Washington    DC          India
1  CUST000178    Pooja Kumar   Fort Worth    TX  United States
2  CUST047516    Sneha Singh       Austin    TX  United States
3  CUST030059   Vihaan Reddy    Charlotte    NC          India
4  CUST048677  Aditya Kapoor  San Antonio    TX         Canada

## Create products table

The products table is designed as a dimension table with one row per product.

Even though product attributes may appear inconsistent in the raw dataset,
we treat ProductID as the primary key and deduplicate accordingly to ensure
a consistent and reliable products table.

In [3]:
# Products: one row per product (deduplicated by ProductID)
df_products = (
    df[
        [
            "ProductID",
            "ProductName",
            "Category",
            "Brand"
        ]
    ]
    .drop_duplicates(subset="ProductID")
    .reset_index(drop=True)
)

df_products.head()

  ProductID          ProductName        Category       Brand
0    P00014           Drone Mini           Books   BrightLux
1    P00040           Microphone  Home & Kitchen  UrbanStyle
2    P00044  Power Bank 20000mAh        Clothing  UrbanStyle
3    P00041       Webcam Full HD  Home & Kitchen      Zenith
4    P00029              T-Shirt        Clothing    KiddoFun

## Create orders table

The orders table contains transactional, order-level data.
It links customers, products, and payment methods together.

In [4]:
# Orders: transactional data (order-level)
df_orders = (
    df[
        [
            "OrderID",
            "OrderDate",
            "CustomerID",
            "ProductID",
            "Quantity",
            "UnitPrice",
            "Discount",
            "Tax",
            "ShippingCost",
            "TotalAmount",
            "OrderStatus",
            "PaymentMethod"
            
        ]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

df_orders.head()

,OrderID,OrderDate,CustomerID,ProductID,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,OrderStatus,PaymentMethod
0,ORD0000001,2023-01-31,CUST001504,P00014,3,106.59,0.00,0.00,0.09,319.86,Delivered,Debit Card
1,ORD0000002,2023-12-30,CUST000178,P00040,1,251.37,0.05,19.10,1.74,259.64,Delivered,Amazon Pay
2,ORD0000003,2022-05-10,CUST047516,P00044,3,35.03,0.10,7.57,5.91,108.06,Delivered,Debit Card
3,ORD0000004,2023-07-18,CUST030059,P00041,5,33.58,0.15,11.42,5.53,159.66,Delivered,Cash on Delivery
4,ORD0000005,2023-02-04,CUST048677,P00029,2,515.64,0.25,38.67,9.23,821.36,Cancelled,Credit Card

## Validate created tables

Perform simple checks to ensure that the tables were created correctly
and contain a reasonable number of rows.

In [5]:
print("Customers:", df_customers.shape)
print("Products:", df_products.shape)
print("Orders:", df_orders.shape)

Customers: (43233, 5)
Products: (50, 4)
Orders: (100000, 12)

## Summary

At this stage, the raw dataset has been successfully split into logical tables
that resemble a relational database structure.

In the next step, we will perform basic data cleaning and prepare the tables
for loading into PostgreSQL.